config/routes.rb
Rails.application.routes.draw do
  get "kiyaku" => "home#kiyaku"
  get "tokutei" => "home#tokutei"
  get "privacy" => "home#privacy"
  get "contact" => "home#contact"
  get "guide" => "home#guide"
  resources :notifications, only: :index
  
  devise_for :users
  root to: "home#index"
  resources :users
  resources :requests do
    collection do
      get 'search'
    end
    resources :proposals
    resources :favorites, only: [:create, :destroy]
  end
  resources :proposals, only: [] do
    patch :confirm_request
    patch :confirm
    patch :proposing
    patch :complete_request
    patch :complete
  end
  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :requests, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  #active_notifications: 自分からの通知
  #passive_notification:　相手からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
   
  def already_favorited?(request)
    self.favorites.exists?(request_id: request.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: current_user.id).pluck(:request_id)
    @favorite_list = Request.find(favorites)
    
    proposals = Proposal.where(user_id: current_user.id).pluck(:request_id)
    @proposal_list = Request.find(proposals)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
    <div class="container">
        <div id="login-row" class="row justify-content-center align-items-center">
            <div id="login-column" class="col-md-10">
                <div id="login-box" class="col-md-12">
                  <section style="background: #f4f8fa;" class="px-5 py-3 my-4">
                        <h3 class="text-center text-info pb-3">プロフィール設定</h3>
                        <%= form_for @user do |f| %>
                        <div class="form-group my-3">
                            <%= f.label :username,"ユーザーネーム", class:"text-info" %><br>
                            <%= f.text_field :username, class: "input w-100" %>
                        </div>

                        <div class="form-group my-3">
                            <%= f.label :email ,"メールアドレス", class:"text-info" %><br>
                            <%= f.text_field :email, class:"input w-100" %>
                        </div>

                        <div class="form-group my-3">
                            <%= f.label :profile, "自己紹介", class:"text-info" %><br>
                            <%= f.text_area :profile, class:"textarea w-100" , rows: "15"%>
                        </div>

                        <div class="form-group my-3">
                            <%= f.label :profile_image, "プロフィール画像", class:"text-info" %><br>
                            <%= f.attachment_field :profile_image, class: "input" %>
                        </div>
                      <div class="text-center my-4">
                        <%= f.submit "プロフィールを更新する", class:"btn btn-info" %>
                      </div>
                      <% end %>
                  </section>
                </div>
            </div>
        </div>
    </div>

app/views/users/show.html.erb
    <div class="container">
     <div class="row">
      <div class="col-lg-4 text-center py-3 my-3" style="background: white;">
        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png",size:'200x200',style: "border-radius: 50%;"%>
        <p><%= @user.username %></p>
        <% if @user.id == current_user.id %>
        <%= link_to "プロフィールを編集する", edit_user_path(@user), class:"btn btn-info"%>
        <% end %>
      </div>
      <div class="col-lg-8 my-3" style="background: white;">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">自己紹介</a>
          </li>
          <% if @user.id == current_user.id %>
            <li class="nav-item">
              <a class="nav-link" id="request-tab" data-toggle="tab" href="#request" role="tab" aria-controls="request" aria-selected="false">自分の依頼</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="proposal-tab" data-toggle="tab" href="#proposal" role="tab" aria-controls="proposal" aria-selected="false">提案済の依頼</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="favorite-tab" data-toggle="tab" href="#favorite" role="tab" aria-controls="favorite" aria-selected="false">お気に入り</a>
            </li>
          <% end %>
        </ul>
          
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active  px-3 py-2" id="home" role="tabpanel" aria-labelledby="home-tab"><%= simple_format @user.profile %></div>
          <% if @user.id == current_user.id %>
          <div class="tab-pane fade px-3 py-2" id="request" role="tabpanel" aria-labelledby="request-tab">
            <div class="row">
              <% @user.requests.each do |request|%>
              <div class="col-md-6">
                <div class="card mb-3" style="<%= request.confirm? ? 'background-color: #a7aaab' : '' %>">
                  <div class="card-body">
                    <%= link_to request_path(request) do %>
                      <p class="card-title textOverflow py-1" style="font-weight: bold;"><%= request.title %></p>
                    <% end %>
                    <div class="image mr-2 mb-2 left">
                      <%= attachment_image_tag request.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
                    </div>
                    <h6 class="card-subtitle text-muted mb-2 pt-2 left"><%= request.user.username %></h6>
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1 clear">
                      <p class="card-text small" style="color: white;">予算：<%= request.budget %></p>
                    </div>
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1">
                      <p class="card-text small" style="color: white;">提案数：<%= request.proposals.count %></p>
                    </div>
                    <div class="row">
                      <div class="col-6">
                        <% if request.confirm? %>
                          <p style="color: red; font-weight: bold; font-size: 12px;" class="pt-2 mb-0">成約済み</p>
                        <% end %>
                      </div>
                      <div class="text-right time pt-2 col-6">
                        <%= request.created_at.to_s(:datetime_jp) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div> 
              <% end %>
            </div>
          </div>
          
          <div class="tab-pane fade show  px-3 py-2" id="proposal" role="tabpanel" aria-labelledby="proposal-tab">
            <div class="row">
              <% @proposal_list.each do |proposal|%>   
              <div class="col-md-6">
                <div class="card mb-3" style="<%= proposal.confirm? ? 'background-color: #a7aaab' : '' %>">  
                  <div class="card-body">
                    <%= link_to request_path(proposal) do %>
                    <p class="card-title textOverflow py-1" style="font-weight: bold;"><%= proposal.title %></p>
                    <% end %>
                    
                    
                    <div class="image mr-2 mb-2 left">
                      <%= attachment_image_tag proposal.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
                    </div>
                    <h6 class="card-subtitle text-muted mb-2 pt-2 left"><%= proposal.user.username %></h6>
                    
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1 clear">
                      <p class="card-text small" style="color: white;">予算：<%= proposal.budget %></p>
                    </div>
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1">
                      <p class="card-text small" style="color: white;">提案数：<%= proposal.proposals.count  %></p>
                    </div>
                    <div class="row">
                      <div class="col-6">
                        <% if proposal.confirm? %>
                          <p style="color: red; font-weight: bold; font-size: 12px;" class="pt-2 mb-0">成約済み</p>
                        <% end %>
                      </div>
                      <div class="text-right time pt-2 col-6">
                        <%= proposal.created_at.to_s(:datetime_jp) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            </div>
          </div>
          
          <div class="tab-pane fade px-3 py-2" id="favorite" role="tabpanel" aria-labelledby="favorite-tab">
            <div class="row">
              <% @favorite_list.each do |post|%>
              <div class="col-md-6">
                <div class="card mb-3" style="<%= post.confirm? ? 'background-color: #a7aaab' : '' %>">
                  <div class="card-body">
                  <%= link_to request_path(post) do %>
                    <p class="card-title textOverflow py-1" style="font-weight: bold;"><%= post.title %></p>
                  <% end %>
                  
                  
                    <div class="image mr-2 mb-2 left">
                      <%= attachment_image_tag post.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
                    </div>
                    <h6 class="card-subtitle text-muted mb-2 pt-2 left"><%= post.user.username %></h6>
                    
                    
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1 clear">
                      <p class="card-text small" style="color: white;">予算：<%= post.budget %></p>
                    </div>
                    <div style="background: #17a2b8;" class="mb-1 px-1 py-1">
                      <p class="card-text small" style="color: white;">提案数：<%= post.proposals.count  %></p>
                    </div>
                    <div class="row">
                      <div class="col-6">
                        <% if post.confirm? %>
                          <p style="color: red; font-weight: bold; font-size: 12px;" class="pt-2 mb-0">成約済み</p>
                        <% end %>
                      </div>
                      <div class="text-right time pt-2 col-6">
                        <%= post.created_at.to_s(:datetime_jp) %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>   
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
     </div>
    </div>