config/routes.rb
Rails.application.routes.draw do
  get "kiyaku" => "home#kiyaku"
  get "tokutei" => "home#tokutei"
  get "privacy" => "home#privacy"
  get "contact" => "home#contact"
  get "guide" => "home#guide"
  resources :notifications, only: :index
  
  devise_for :users
  root to: "home#index"
  resources :users
  resources :requests do
    collection do
      get 'search'
    end
    resources :proposals
    resources :favorites, only: [:create, :destroy]
  end
  resources :proposals, only: [] do
    patch :confirm_request
    patch :confirm
    patch :proposing
    patch :complete_request
    patch :complete
  end
  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :user
    has_many :proposals
    has_many :favorites, dependent: :destroy
    has_many :rooms, dependent: :destroy
    has_many :notifications, dependent: :destroy
    
    enum status: [:requesting, :confirm, :confirm_request]
    
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and request_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        request_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_proposal!(current_user, proposal_id)
    # すでに「提案」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and request_id = ? and action = ? ", current_user.id, user_id, id, 'proposal'])
    # 提案されていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        request_id: id,
        visited_id: user_id,
        action: 'proposal'
      )
      notification.save if notification.valid?
    end
  end
  
  def create_notification_confirm_request!(current_user, proposal_user_id)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: proposal_user_id,
      action: 'confirm_request'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_complete_request!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'complete_request'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_complete!(current_user, proposal_user_id)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: proposal_user_id,
      action: 'complete'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_reject!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'reject'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_confirm!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'confirm'      
    )
    notification.save if notification.valid?
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_q, only: [:index, :search]
  
  def index
    @requests = Request.all
    @requests = Request.page(params[:page]).order(id: "DESC").per(8)
  end

  def show
    @request = Request.find(params[:id])    
    @proposal = @request.proposals.find_by(user: current_user)
  end

  def new
    @request = Request.new
  end
  
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    @request.status = 'requesting'
    @request.save
    redirect_to requests_path
  end

  def edit
    @request = Request.find(params[:id])
  end
  
  def update
    @request = Request.find(params[:id])
    @request.update(request_params)
    redirect_to requests_path
  end
  
  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path
  end
  
  def search
    @requests = Request.all
    @results = @q.result
  end
  
  private
  
  def set_q
    @q = Request.ransack(params[:q])
  end
  
  def request_params
    params.require(:request).permit(:title, :budget, :text)
  end
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
    <section style="background:  #f4f8fa;;">
      <div class="container">
        <div class="row py-5">
          <div class="left col-4">
            <div class="text-center py-3" style="background: white;">
              <%= attachment_image_tag @request.user, :profile_image, fallback: "no-image.png",size:'200x200',style: "border-radius: 50%;"%>
              <p><%= @request.user.username%></p>
              <%= link_to "プロフィール", user_path(@request.user), class:"btn btn-info w-75 mb-1"  %>            
            </div>
          </div>
          <div class="right col-8 px-3" style="background: white;">
            <%= form_for @request do |f|%>
            <h4 class="my-4 text-info" style="font-weight: bold;">依頼を編集する</h4>
              <div class="form-group my-3">
                <%= f.label :"依頼のタイトル:", class:"text-info" %><br>
                <%= f.text_field :title, class:"w-100" %>
              </div>
              <div class="form-group my-3">
                <%= f.label :"予算:", class:"text-info" %><br>
                <%= f.text_field :budget, class:"w-100" %>
              </div>
              <div class="form-group">
                <%= f.label :"依頼の詳細:", class:"text-info" %><br>
                <%= f.text_area :text, class:"w-100", rows:"15" %>
              </div>
  
              <div class="text-center pb-3">
                <%= f.submit "変更する", class:"btn btn-info" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>

app/views/requests/index.html.erb
<div class="container">
  <h2 class="text-center mt-5 text-info">募集中の依頼</h2>
  
  <div class="input-group d-flex justify-content-center">
    <%= search_form_for @q, url: search_requests_path do |f| %>
      <%= f.search_field :title_cont, placeholder:"キーワードを入力してください", class:"py-2 form_size left", size: "40%" %>
      <div class="sm_only left">
        <%= f.submit '検索', class:"btn btn-info mb-5" %>            
      </div>
  </div>
  <div class="md_only text-center">
    <%= f.submit '検索', class:"btn btn-info mt-1 mb-3" %> 
  </div>
    <% end %>
    
  <div class="row ">
    <% @requests.each do |request| %>
      <div class="col-md-6">
        <div class="card mb-3" style="<%= request.confirm? ? 'background-color: #a7aaab' : '' %>">
          <div class="card-body">
            <%= link_to request_path(request) do %>
              <p class="card-title textOverflow py-1" style="font-weight: bold;"><%= request.title %></p>
            <% end %>
            
            <div class="image mr-2 mb-2 left">
              <%= attachment_image_tag request.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
            </div>
            <h6 class="card-subtitle text-muted pt-2 left"><%= request.user.username %></h6>

            <div style="background: #17a2b8;" class="mb-1 px-1 py-1 clear">
              <p class="card-text small" style="color: white;">予算：<%= request.budget %></p>
            </div>
            <div style="background: #17a2b8;" class="mb-1 px-1 py-1">
              <p class="card-text small" style="color: white;">提案数：<%= request.proposals.count %></p>
            </div>
            <div class="text-right">
              <% if current_user.already_favorited?(request) %>
                <% favorite = current_user.favorites.find_by(request_id: request.id) %>
                <%= link_to  request_favorite_path(request, favorite), method: :delete do %>
                  <i class="fas fa-heart"></i>
                  <%= request.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to request_favorites_path(request), method: :post do%>
                  <i class="far fa-heart"></i>
                  <%= request.favorites.count %>
                <% end %>
              <% end %>
            </div>
            <div class="row">
              <div class="col-6">
                <% if request.confirm? %>
                  <p style="color: red; font-weight: bold; font-size: 12px;" class="pt-2 mb-0">成約済み</p>
                <% end %>
              </div>
              <div class="text-right time pt-2 col-6">
                <%= request.created_at.to_s(:datetime_jp) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @requests%>
  <div class="mb-5"></div>
</div>

app/views/requests/new.html.erb
<section style="background:  #f4f8fa;;">
  <div class="container">
    <div class="row py-5">
      <div class="left col-lg-4 my-1">
        <div class="text-center py-3" style="background: white;">
          <%= attachment_image_tag current_user, :profile_image, fallback: "no-image.png",size:'200x200',style: "border-radius: 50%;"%>
          <p><%= current_user.username %></p>
          <button type="button" class="btn btn-info w-75 mb-3">プロフィール</button>
        </div>
      </div>
      <div class="right col-lg-8 px-3 py-3 my-1" style="background: white;">
        <h4 class="text-info" style="font-weight: bold;">依頼を作成する</h4>
          <%= form_for @request do |f| %>
            <div class="form-group my-3">
                <%= f.label :"依頼のタイトル:",class:"text-info" %><br>
                <%= f.text_field :title,class:"w-100",placeholder:"50文字以内で入力してください" %>
            </div>
            <div class="form-group my-3">
                <%= f.label :"予算:", class:"text-info" %><br>
                <%= f.text_field :budget, class:"w-100",placeholder:"例:5000円〜10000円で検討中" %>
            </div>
            <div class="form-group my-3">
                <%= f.label :"依頼の詳細:", class:"text-info" %><br>
                <%= f.text_area :text, class:"w-100", rows:"15",placeholder:"出来るだけ詳しく記述してください" %>
            </div>
            <div class="text-center">
                <%= f.submit "依頼を投稿する", class:"btn btn-info" %>
            </div>
      </div>
      <% end %>
    </div>
  </div>
</section>
    

app/views/requests/search.html.erb
<div class="container">
  <h2 class="pb-2 text-center py-4 text-info">検索結果</h2>
  <div class="row">
    <% @results.each do |request| %>
      <div class="col-md-6">
        <div class="card mb-3" style="<%= request.confirm? ? 'background-color: #a7aaab' : '' %>">
          <div class="card-body">
            <%= link_to request_path(request) do %>
              <h5 class="card-title textOverflow py-1"><%= request.title %></h5>
            <% end %>
            <div class="image mr-2 mb-2 left">
              <%= attachment_image_tag request.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
            </div>
            <h6 class="card-subtitle text-muted mb-2 pt-2 left"><%= request.user.username %></h6>
            <div style="background: #17a2b8;" class="mb-1 px-1 py-1 clear">                  
              <p class="card-text small" style="color: white;">予算：<%= request.budget %></p>
            </div>
            <div style="background: #17a2b8;" class="mb-1 px-1 py-1">
              <p class="card-text small" style="color: white;">提案数：<%= request.proposals.count %></p>
            </div>
            <div class="text-right">
              <% if current_user.already_favorited?(request) %>
                <% favorite = current_user.favorites.find_by(request_id: request.id) %>
                <%= link_to  request_favorite_path(request, favorite), method: :delete do %>
                <i class="fas fa-heart"></i>
                <%= request.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to request_favorites_path(request), method: :post do%>
                <i class="far fa-heart"></i>
                <%= request.favorites.count %>
                <% end %>
              <% end %>
            </div>
            <div class="row">
              <div class="col-6">
                <% if request.confirm? %>
                  <p style="color: red; font-weight: bold; font-size: 12px;" class="pt-2 mb-0">成約済み</p>
                <% end %>
              </div>
                <div class="text-right time pt-2 col-6">
                <%= request.created_at.to_s(:datetime_jp) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
　<%= link_to '依頼一覧に戻る', requests_path, class:"d-flex justify-content-center pb-3" %>
</div>

app/views/requests/show.html.erb
<section style="background:#f4f8fa;">
  <div class="container">
    <div class="row py-5">
      <div class="left col-lg-4">
        <div class="text-center py-3">
          <%= attachment_image_tag @request.user, :profile_image, fallback: "no-image.png",size:'200x200',style: "border-radius: 50%;"%>
          <p><%= @request.user.username%></p>
          <%= link_to "プロフィール", user_path(@request.user), class:"btn btn-info w-75 mb-1"  %>
        </div>
      </div>
      <div class="right col-lg-8" style="background: white;">
        <div class="detail-top">
          <div class="detail-title px-2 py-3">
            <p class="mb-0" style="font-weight: bold;"><%= @request.title %></p>
          </div>
          <div class="w-100 py-1 pl-2" style="background: #f4f8fa;">予算：<%= @request.budget %></div>
          <div class="w-100 py-1 pl-2 my-2" style="background: #f4f8fa;">提案数：<%= @request.proposals.count %></div>
          <p class="px-2"><%= simple_format @request.text %></p>
          <div class="text-right pr-2 mb-2">
            <% if current_user.already_favorited?(@request) %>
              <% favorite = current_user.favorites.find_by(request_id: @request.id) %>
              <%= link_to  request_favorite_path(@request, favorite), method: :delete do %>
                <i class="fas fa-heart"></i>
                <%= @request.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to request_favorites_path(@request), method: :post do%>
                <i class="far fa-heart"></i>
                <%= @request.favorites.count %>
              <% end %>
            <% end %>
          </div>
        </div>
        <% if @request.user.id == current_user.id %>
        <div class="text-center">
            <%= link_to request_path(@request), method: :delete do %>
              <div class="btn btn-danger mb-2 <%= "none" if @request.confirm? %>" data= confirm: "削除しますか">削除する</div>
            <% end %> 
            <%= link_to edit_request_path(@request) do %>
              <div class="btn btn-info mb-2 <%= "none" if @request.confirm? %>">編集する</div>
            <% end %>
        </div>
        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  提案を確認する(<%= @request.proposals.count %>件)
                </button>
              </h5>
            </div>
            <% @request.proposals.each do |proposal|%>
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card-body px-0">
                <div class="form-group" style="border: solid 1px;">
                  <p class="text-center" style="background: #f4f8fa;"><span style="font-weight: bold;"><%= proposal.user.username %></span> さんから提案が届きました</p>
                  <p class="px-2">予算：<%= proposal.budget %>円</p>
                  <p class="px-2"><%= simple_format proposal.text %></p>
                  <div class="text-center pb-2">
                    <%= link_to rooms_path(request_id: @request.id, proposal_id: proposal.id), method: :post do %>
                      <button type="button" class="btn btn-info <%= "none" if @request.confirm? %>">メッセージを送る</button>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
        <% elsif @proposal.nil? %>
          <div class="text-center">
            <%= link_to  new_request_proposal_path(@request) do %>
              <div class="btn btn-info <%= "none" if @request.confirm? %>" data= confirm: "提案しますか">提案する</div>
            <% end %>
          </div>
        <% else %>
          <div class="accordion" id="accordionExample">
            <h5 class="mb-0">
            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              自分の提案を確認する
            </button>
            </h5>
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card">
                <div class="card-body px-0 py-0" style="border: solid 1px;">
                  <div class="w-100 pl-2 proposal-txt" style="background: #f4f8fa;">予算：<%= @proposal.budget %>円</div>
                  <p class="proposal-txt px-2 py-2"><%= simple_format @proposal.text %></p>                          
                </div>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</section>