config/routes.rb
Rails.application.routes.draw do
  get "kiyaku" => "home#kiyaku"
  get "tokutei" => "home#tokutei"
  get "privacy" => "home#privacy"
  get "contact" => "home#contact"
  get "guide" => "home#guide"
  resources :notifications, only: :index
  
  devise_for :users
  root to: "home#index"
  resources :users
  resources :requests do
    collection do
      get 'search'
    end
    resources :proposals
    resources :favorites, only: [:create, :destroy]
  end
  resources :proposals, only: [] do
    patch :confirm_request
    patch :confirm
    patch :proposing
    patch :complete_request
    patch :complete
  end
  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :request
  belongs_to :proposal
  has_many :messages
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    requests = current_user.requests
    proposals = current_user.proposals
    @rooms = Room.where(request: requests).or(Room.where(proposal: proposals)).order(latest_message_created_at: :desc)
  end

  def show
    @message = Message.new
    @room = Room.find(params[:id])
    @messages = @room.messages
    
   
  end

  def create
    request = current_user.requests.find(params[:request_id])
    proposal = request.proposals.find(params[:proposal_id])

    request.rooms.find_or_create_by(proposal: proposal)
    redirect_to rooms_path
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="container my-5" style="background: white;"> 
  <h1 class="text-center py-4">メッセージ一覧</h1>
  <div class="table-responsive">
    <table class="table table-bordered text-nowrap">
      <thead style="background: #17a2b8; color: white;">
        <tr>
          <th class="th1">ユーザー名</a></th>              
          <th class="th2">依頼のタイトル</th>
          <th class="th3">最新日時</th>
          <th class="th3"></th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= attachment_image_tag room.proposal.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
              <%= room.request.user == current_user ? room.proposal.user.username : room.request.user.username %></td>
            <td>
              <%= link_to request_path(room.request) do %>
                <p><%= room.request.title%></p>
              <% end %>
            </td>
            <td><%= room.latest_message_created_at.present? ? room.latest_message_created_at.strftime("%Y/%m/%d %H:%M") : '' %></td>
            <td><%= link_to 'メッセージを見る', room_path(room) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container my-3" style="background: white;">
    <div class="text-center">
      <% if @room.proposal.complete? %>
        <p class="complete-msg">この依頼は取引が完了しています</p>
      <% elsif @room.request.confirm? %>
        <p class="confirm-msg mb-0">この依頼は取引が成立している為、新規で確定依頼のやりとりをすることはできません</p>
      <% end %>
      
        <% if @room.proposal.confirm? && @room.proposal.user == current_user %>
          <div class="complete-alert py-2">
            <p style="color: white;" class="mb-0">依頼を実行完了したら、ボタンを押してください。</p>
            <p id="open" class="mb-0 mx-auto " style="color: white; border-bottom: 1px solid #F7F7F7;">完了の詳細をみる</p>
              <div id="mask" class="hidden"></div>
              <section id="modal" class="hidden">
                <p>依頼を実行完了したことが相手に通知されます。<br>相手が承認すると支払いが実行されます。</p>
                <div id="close">
                  閉じる
                </div>
              </section>
              <%= javascript_include_tag('application.js') %>
            <%= form_for @room.proposal, url: proposal_complete_request_path(@room.proposal), method: :patch, remote: false do |f| %>
              <%= f.submit '完了', class: 'btn btn-secondary',data: { confirm: "依頼内容を実行完了した通知を相手に送ります。"} %>
            <% end %>
          </div>
        <% end %>
        
      <p class="my-3" style="font-weight: bold;"><%= @room.request.title %></p>
      <p class="pb-1 mb-0">メッセージの相手：
      <% if @room.request.user == current_user %>
        <%= attachment_image_tag @room.proposal.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
      <% else %>
        <%= attachment_image_tag @room.request.user, :profile_image, fallback: "no-image.png",size:'30x30',style: "border-radius: 50%;"%>
      <% end %>  
      <span style="font-weight: bold;"><%= @room.request.user == current_user ? @room.proposal.user.username : @room.request.user.username %></span></p>
        <% if @room.request.user == current_user && @room.proposal.proposing? && @room.proposal.request.requesting? %>
          <div class="message-alert mb-4 pt-1">
            <p id="open" class="mb-1 mb-2 mx-auto " style="color: white; border-bottom: 1px solid #F7F7F7;">確定依頼の詳細をみる</p>
            <div id="mask" class="hidden"></div>
            <section id="modal" class="hidden">
              <p>ボタンを押すと、入力した金額での確定依頼メッセージが相手に送信され、<br>それ以降は金額の変更ができなくなります。<br><br>
              相手が提示された金額で承諾をすると取引が成立し、決済が行われます。</p>
              <div id="close">
                閉じる
              </div>
            </section>
            <%= javascript_include_tag('application.js') %>
            
           <%= form_for @room.proposal, url: proposal_confirm_request_path(@room.proposal), method: :patch, remote: false do |f| %>
               <%= f.number_field :last_budget %>円
               <%= f.submit "確定依頼をする", class:"btn btn-info btn-sm" %>
           <% end %>
           
          </div>
        <% end %>
      
    </div>
    
    <% @messages.each do |message| %>
      <% if message.user == current_user %>
        <div class="mb-2 text-item1">
           <p class="text-left"><%= message.text.html_safe %></p>
           <p class="text-right my-0"><%= message.created_at.strftime("%-m/%d %H:%M") %></p>
        </div>
      <% else %>
        <div class="my-3 py-2 text-item2">
          
           <p class="text-left mb-0 px-2"><%= message.text.html_safe %></p>
           <% if message.confirm_request? %>
             <div class="example">
               <%= form_for @room.proposal, url: proposal_confirm_path(@room.proposal), method: :patch, remote: false do |f| %>
                 <%= f.hidden_field :message_id, :value => message.id %>
                 
                 <%= f.submit '承諾する', class: 'btn btn-info',style:"float:left;", data: { confirm: "承認すると取引が成立し金額の変更ができなくなります。よろしいですか？"} %>
                 
               <% end %>
               <%= form_for @room.proposal, url: proposal_proposing_path(@room.proposal), method: :patch, remote: false do |f| %>
               
                 <%= f.hidden_field :message_id, :value => message.id %>
                 
                 <%= f.submit '差し戻す', class: 'btn btn-danger ml-1',style:"float:left;", data: { confirm: "差し戻しますか？"} %>
               <% end %>             
             </div>
           <% end %>
           <% if message.complete_request? %>
              <%= form_for @room.proposal, url: proposal_complete_path(@room.proposal), method: :patch, remote: false do |f| %>
                <%= f.hidden_field :message_id, :value => message.id %>

                  <%= f.submit '確認', class: 'btn btn-danger',data: { confirm: "確認すると取引が完了します？"} %>

              <% end %>   
           <% end %>
               
           <p class="text-right mb-0 px-2 clear"><%= message.created_at.strftime("%-m/%d %H:%M") %></p> 
           
        </div>
      <% end %>

    <% end %>
    <div class="text-center">
      <%= form_for @message, url: room_messages_path(@room) do |f| %>
        <div class="form-group mb-0">
          <%= f.text_area :text, class:"w-100 px-2", placeholder:"メッセージを入力してください", rows:"5" %>
        </div>
          <%= f.submit "送信する", class:"btn btn-info" %>
      <% end %>
    </div>
</div>