config/routes.rb
Rails.application.routes.draw do
  get "kiyaku" => "home#kiyaku"
  get "tokutei" => "home#tokutei"
  get "privacy" => "home#privacy"
  get "contact" => "home#contact"
  get "guide" => "home#guide"
  resources :notifications, only: :index
  
  devise_for :users
  root to: "home#index"
  resources :users
  resources :requests do
    collection do
      get 'search'
    end
    resources :proposals
    resources :favorites, only: [:create, :destroy]
  end
  resources :proposals, only: [] do
    patch :confirm_request
    patch :confirm
    patch :proposing
    patch :complete_request
    patch :complete
  end
  resources :rooms, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :request
  
  validates_uniqueness_of :request_id, scope: :user_id

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  enum display_type: [:normal, :confirm_request, :complete_request]
end

app/models/notification.rb
class Notification < ApplicationRecord
  #新しい通知からデータを取得する
  default_scope -> { order(created_at: :desc) }
  belongs_to :request, optional: true
  belongs_to :proposal, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/proposal.rb
class Proposal < ApplicationRecord
    belongs_to :request
    belongs_to :user
    has_one :room
    
    has_many :notifications, dependent: :destroy
    enum status: [:proposing, :confirm, :confirm_request, :complete, :complete_request]
end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :user
    has_many :proposals
    has_many :favorites, dependent: :destroy
    has_many :rooms, dependent: :destroy
    has_many :notifications, dependent: :destroy
    
    enum status: [:requesting, :confirm, :confirm_request]
    
  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and request_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        request_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_proposal!(current_user, proposal_id)
    # すでに「提案」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and request_id = ? and action = ? ", current_user.id, user_id, id, 'proposal'])
    # 提案されていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        request_id: id,
        visited_id: user_id,
        action: 'proposal'
      )
      notification.save if notification.valid?
    end
  end
  
  def create_notification_confirm_request!(current_user, proposal_user_id)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: proposal_user_id,
      action: 'confirm_request'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_complete_request!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'complete_request'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_complete!(current_user, proposal_user_id)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: proposal_user_id,
      action: 'complete'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_reject!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'reject'      
    )
    notification.save if notification.valid?
  end
  
  def create_notification_confirm!(current_user)

    notification = current_user.active_notifications.new(
      request_id: id,
      visited_id: user_id,
      action: 'confirm'      
    )
    notification.save if notification.valid?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :request
  belongs_to :proposal
  has_many :messages
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :requests, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  #active_notifications: 自分からの通知
  #passive_notification:　相手からの通知
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
   
  def already_favorited?(request)
    self.favorites.exists?(request_id: request.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @requests = Request.all
  end
  def kiyaku
  end
  def tokutei
  end
  def privacy
  end
  def contact
  end
  def guide
  end 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    requests = current_user.requests
    proposals = current_user.proposals
    @rooms = Room.where(request: requests).or(Room.where(proposal: proposals)).order(latest_message_created_at: :desc)
  end

  def show
    @message = Message.new
    @room = Room.find(params[:id])
    @messages = @room.messages
    
   
  end

  def create
    request = current_user.requests.find(params[:request_id])
    proposal = request.proposals.find(params[:proposal_id])

    request.rooms.find_or_create_by(proposal: proposal)
    redirect_to rooms_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: current_user.id).pluck(:request_id)
    @favorite_list = Request.find(favorites)
    
    proposals = Proposal.where(user_id: current_user.id).pluck(:request_id)
    @proposal_list = Request.find(proposals)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <title>Solve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/d53d95315b.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class="notification">
      <p class="notice my-0"><%= notice %></p>
    </div>  
  <% end %>
  <% if flash[:alert] %>
    <div class="notification">
      <p class="alert my-0"><%= alert %></p>
    </div>
  <% end %>
    
  <% if user_signed_in? %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light px-4 py-0">
        <div class="mr-auto">
          <%= link_to root_path ,class:"navbar-brand" do %>
            <%= image_tag "main.png", class:"img2" %>
          <% end %>
        </div>
        <div>
          <button class="navbar-toggler">
            <span class="navbar-toggler-icon" data-toggle="collapse" data-target="#menu"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "ご利用ガイド", guide_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "依頼をする", new_request_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "依頼を受ける", requests_path, class:"nav-link"%>
              </li>
              <li class="nav-item"><%= link_to 'メッセージ', rooms_path, class: 'nav-link' %></li>
              <li class="nav-item"><%= link_to "通知#{@unread_notification_count > 0 ? '(' + @unread_notification_count.to_s + ')' : ''}", notifications_path, class: 'nav-link' %></li> 
              <li class="nav-item">
                <%= link_to "プロフィール", user_path(current_user), class:"nav-link"%>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class:"nav-link"%>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% else %>
    <header>
      <nav class="navbar navbar-expand-sm navbar-light px-4 py-0">
        <div class="mr-auto">
          <%= link_to root_path ,class:"navbar-brand" do %>
            <%= image_tag "main.png", class:"img2" %>
          <% end %>
        </div>
        <div>
          <button class="navbar-toggler">
            <span class="navbar-toggler-icon" data-toggle="collapse" data-target="#menu"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class:"nav-link"%>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  <% end %>
  <div style="background: #13b1c0;">
    <p class="text-center mb-0" style="color: white;">一部機能に制限をかけております</p>
  </div>
  <main>
  <%= yield %>
  </main>
  <div style="background: #13b1c0;">
    <p class="text-center mb-0" style="color: white;">一部機能に制限をかけております</p>
  </div>
  <footer>
    <div class="container">
      <nav class="navbar navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "ご利用ガイド", guide_path, class:"nav-link py-0"%>
          </li>
          <li class="nav-item">
            <%= link_to "利用規約", kiyaku_path, class:"nav-link py-0"%>
          </li>
          <li class="nav-item">
            <%= link_to "特定商取引に基づく表記", tokutei_path, class:"nav-link py-0"%>        
          </li>
          <li class="nav-item">
            <%= link_to "プライバシーポリシー", privacy_path, class:"nav-link py-0"%>
          </li>
          <li class="nav-item">
            <%= link_to "お問い合わせ", contact_path, class:"nav-link py-0"%>
          </li>
        </ul>
      </nav>
    </div>
  </footer>
  </body>
</html>